title: "Collectif Végé | Veggie Collective"
description: "Organisme sans but lucratif à Gatineau où nous plantons, cultivons et récoltons ensemble. / A non-profit in Gatineau where we plant, grow and harvest together."
baseurl: "/collectif-vege"
url: "https://etienne-lefebvre.github.io"
email: "collectifvege.veggiecollective@gmail.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
